services:
  mysql:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mysql_refugio_db
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: refugio
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
